<?php

    require 'vendor/autoload.php';
    require 'src/classes/Usuario.php';
    require 'src/classes/Accommodation.php';

    use PHPSupabase\Service;
    use Dotenv\Dotenv;

    // Load environment variables from .env file
    $dotenv = Dotenv::createImmutable(__DIR__);
    $dotenv->load();
    // Replace with your actual Supabase API key and URL
    // Access environment variables using $_ENV
    $apiKey = $_ENV['VITE_SUPABASE_ANON_KEY'] ?? null;
    $apiUrl = $_ENV['VITE_SUPABASE_URL'] ?? null;

    if (!$apiKey || !$apiUrl) {
        die('Environment variables VITE_SUPABASE_ANON_KEY or VITE_SUPABASE_URL are not set.');
    }

    echo $apiKey;

    // Create a Service instance
    $service = new Service($apiKey, $apiUrl);

    // Example: Create an Auth instance and sign in a user
    $auth = $service->createAuth();
    try {
        $auth->signInWithEmailAndPassword('admin@example.com', '123456');
        $data = $auth->data();
        echo 'User signed in successfully. Access token: ' . $data->access_token;
    } catch (Exception $e) {
        echo 'Error: ' . $auth->getError();
    }

  
    $db = $service->initializeDatabase('accommodations');
    $accommodation = new Accommodation($db);
    // Leer todos los usuarios
    $accommodations = $accommodation->read();
    print_r($accommodations);
   

        /*
    $db = $service->initializeDatabase('usuarios');
    $usuario = new Usuario($db);
    // Leer todos los usuarios
    $usuarios = $usuario->read();
    print_r($usuarios);
    */

    /*

    // Create a Database instance
    $db = $service->initializeDatabase('usuarios');

    // Crear una instancia de Usuario
    $usuario = new Usuario($db);

    // Crear un nuevo usuario
    $usuario->nombre = 'Josh Palacios';
    $usuario->email = 'orlando.palaciosv@gmail.com';
    $usuario->contrasena = 'password123';
    $usuario->fecha_nacimiento = '1990-01-01';
    $usuario->genero = 'Masculino';
    $usuario->foto_perfil = 'https://example.com/foto.jpg';
    //$usuario->create();

    if ($usuario->create()) {
        echo "Usuario creado exitosamente.\n";
        $auth = $service->createAuth();

        try{
            $auth->createUserWithEmailAndPassword($usuario->email, $usuario->contrasena);
            $data = $auth->data(); // get the returned data generated by request
            echo 'User has been created! A confirmation link has been sent to the '. $data->email;
        }
        catch(Exception $e){
            echo $auth->getError();
        }

    } else {
        echo "Error al crear el usuario.\n";
    }

    // Leer todos los usuarios
    $usuarios = $usuario->read();
    print_r($usuarios);


*/

    // Actualizar un usuario
    /*$usuario->nombre = 'Juan Perez Actualizado';
    $usuario->email = 'juan.perez.actualizado@example.com';
    $usuario->contrasena = 'newpassword123';
    $usuario->fecha_nacimiento = '1990-01-01';
    $usuario->genero = 'Masculino';
    $usuario->foto_perfil = 'https://example.com/foto_actualizada.jpg';
    $usuario->update('1');*/

    // Example: Create a Database instance and fetch all records from a table
    /*$db = $service->initializeDatabase('your_table_name');
    try {
        $records = $db->fetchAll()->getResult();
        print_r($records);
    } catch (Exception $e) {
        echo 'Error: ' . $db->getError();
    }*/
?>